name: Rhythmic Running
favicon: null
layout_spectrum: 0.01509
typography_spectrum: 0.21533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#fff200'
    - '#2c2c2c'
    - '#606060'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
