name: Rhythmic Running
favicon: null
layout_spectrum: 0.24428
typography_spectrum: 0.31523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8aaf45'
    - '#295500'
    - '#678a36'
    - '#bbd896'
    - '#112600'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
