name: Rhythmic Running
favicon: null
layout_spectrum: 0.40687
typography_spectrum: 0.31523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b39002'
    - '#d2b60c'
    - '#efd21c'
    - '#efdc91'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
