name: Rhythmic Running
favicon: null
layout_spectrum: 0.01509
typography_spectrum: 0.21533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b39002'
    - '#d2b60c'
    - '#efd21c'
    - '#efdc91'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
